package com.rocayasociados.extensionbackend.codegen

import com.squareup.javapoet.AnnotationSpec
import com.squareup.javapoet.ClassName
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.MethodSpec
import com.squareup.javapoet.ParameterSpec
import com.squareup.javapoet.TypeSpec
import javax.lang.model.element.Modifier

/**
 * The fixed, non-configurable-in-this-iteration parts of the generated
 * project: build file, application entry point, and a placeholder properties
 * file. See design.md - "Fixed generated-project shape".
 */
object ProjectScaffold {
    const val BASE_PACKAGE = "com.generated.app"
    const val ENTITY_PACKAGE = "$BASE_PACKAGE.entity"
    const val REPOSITORY_PACKAGE = "$BASE_PACKAGE.repository"

    private const val JAVA_VERSION = "25"
    private const val SPRING_BOOT_VERSION = "4.1.1"

    fun applicationJavaFile(): JavaFile {
        val springBootApplication = ClassName.get("org.springframework.boot.autoconfigure", "SpringBootApplication")
        val springApplication = ClassName.get("org.springframework.boot", "SpringApplication")

        val mainMethod = MethodSpec.methodBuilder("main")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(Void.TYPE)
            .addParameter(ParameterSpec.builder(Array<String>::class.java, "args").build())
            .addStatement("\$T.run(Application.class, args)", springApplication)
            .build()

        val applicationClass = TypeSpec.classBuilder("Application")
            .addAnnotation(AnnotationSpec.builder(springBootApplication).build())
            .addModifiers(Modifier.PUBLIC)
            .addMethod(mainMethod)
            .build()

        return JavaFile.builder(BASE_PACKAGE, applicationClass).build()
    }

    fun applicationProperties(): String = """
        # Generated by ApollonCASE. Fill in a real datasource before running this project.
        spring.datasource.url=jdbc:postgresql://localhost:5432/${'$'}{DB_NAME:app}
        spring.datasource.username=${'$'}{DB_USER:app}
        spring.datasource.password=${'$'}{DB_PASSWORD:app}
        spring.jpa.hibernate.ddl-auto=update
    """.trimIndent() + "\n"

    fun pomXml(): String = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>

            <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>$SPRING_BOOT_VERSION</version>
                <relativePath/>
            </parent>

            <groupId>com.generated</groupId>
            <artifactId>app</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <name>app</name>
            <description>Generated by ApollonCASE from a class diagram</description>

            <properties>
                <java.version>$JAVA_VERSION</java.version>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-data-jpa</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </project>
    """.trimIndent() + "\n"
}
