spring.datasource.url=jdbc:postgresql://10.50.1.53:50001/apolloncase
spring.datasource.username=apolloncase
spring.datasource.password=ucZKpHyrVJnXRGBDEhLR
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://10.50.1.53:9000/realms/ApollonCASE